# Generated by Django 5.0.1 on 2025-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
